<?php
/**
 * Created by PhpStorm.
 * User: aleonov
 * Date: 07.04.2017
 * Time: 19:16
 */

namespace app\components;


use yii\bootstrap\Widget;

class FooterMenuWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
    }
    public function run()
    {
        return $this->render('my', [
            'pn' => $this->pn,
            'title' => $this->title,
            'price' => $this->price,
        ]);

    }
    
}